setwd("/Users/User/Desktop/GS Comparison/")
files <- list.files(pattern = "\\.csv$", recursive = TRUE)
data2=lapply(files, read.table, header=T, sep=",")
anna <- data.frame()
for (i in 1:length(data2)){
  a <- data2[[i]]
  b <- length(a[,1])
  c <- a[with(a,order(Standard)),]
  d <- ceiling(b*.01) 
  e <- ceiling(b*.05)
  g <- ceiling(b*.1)
  h <- ceiling(b*.25)
  bd <- mean(c$Pheno[1:d])
  be <- mean(c$Pheno[1:e])
  bg <- mean(c$Pheno[1:g])
  bh <- mean(c$Pheno[1:h])
  td <- mean(c$Pheno[(b-d):b])
  te <- mean(c$Pheno[(b-e):b])
  tg <- mean(c$Pheno[(b-g):b])
  th <- mean(c$Pheno[(b-h):b])
  j <- a[with(a,order(PATRIOT)),]
  cd <- mean(j$Pheno[1:d])
  ce <- mean(j$Pheno[1:e])
  cg <- mean(j$Pheno[1:g])
  ch <- mean(j$Pheno[1:h])
  ud <- mean(j$Pheno[(b-d):b])
  ue <- mean(j$Pheno[(b-e):b])
  ug <- mean(j$Pheno[(b-g):b])
  uh <- mean(j$Pheno[(b-h):b])
  gb <- a[with(a,order(GBLUP)),]
  gd <- mean(gb$Pheno[1:d])
  ge <- mean(gb$Pheno[1:e])
  gg <- mean(gb$Pheno[1:g])
  gh <- mean(gb$Pheno[1:h])
  kd <- mean(gb$Pheno[(b-d):b])
  ke <- mean(gb$Pheno[(b-e):b])
  kg <- mean(gb$Pheno[(b-g):b])
  kh <- mean(gb$Pheno[(b-h):b])
  q1 <- cor(a$Standard,a$Pheno)
  q2 <- cor(a$PATRIOT,a$Pheno)
  q3 <- cor(a$GBLUP,a$Pheno)
  anna[i,1] <- bd
  anna[i,2] <- be     
  anna[i,3] <- bg
  anna[i,4] <- bh 
  anna[i,5] <- td   
  anna[i,6] <- te
  anna[i,7] <- tg 
  anna[i,8] <- th     
  anna[i,9] <- files[[i]]
  anna[i,10] <- mean(c$Pheno)
  anna[i,11] <- cd
  anna[i,12] <- ce     
  anna[i,13] <- cg
  anna[i,14] <- ch 
  anna[i,15] <- ud   
  anna[i,16] <- ue
  anna[i,17] <- ug 
  anna[i,18] <- uh 
  anna[i,19] <- gd
  anna[i,20] <- ge     
  anna[i,21] <- gg
  anna[i,22] <- gh 
  anna[i,23] <- kd   
  anna[i,24] <- ke
  anna[i,25] <- kg 
  anna[i,26] <- kh 
  anna[i,27] <- q1
  anna[i,28] <- q2 
  anna[i,29] <- q3 
  }
colnames(anna) <- c("Bottom 1%R","Bottom 5%R","Bottom 10%R","Bottom 25%R","Top 1%R", "Top 5%R","Top 10%R", "Top 25%R", "File name","Testing set average","Bottom 1%P","Bottom 5%P","Bottom 10%P","Bottom 25%P","Top 1%P", "Top 5%P","Top 10%P", "Top 25%P","Bottom 1%G","Bottom 5%G","Bottom 10%G","Bottom 25%G","Top 1%G", "Top 5%G","Top 10%G", "Top 25%G","CorrelR","CorrelP","CorrelG")
write.csv(anna,"Genomic selection effectiveness_raw.csv")
